# Generated by Django 4.2.9 on 2024-11-15 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_id", models.CharField(default=1, max_length=255)),
                ("canvas_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("points_possible", models.IntegerField(blank=True, null=True)),
                (
                    "submission_types",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(default=1, max_length=255)),
                ("created_at", models.DateTimeField()),
                ("course_code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("workflow_state", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CustomTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateTimeField()),
                ("complete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Deadlines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canvas_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("deadline_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="fileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=255, unique=True)),
                ("filename", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("size", models.IntegerField()),
                ("content_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canvas_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("sortable_name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=255)),
                ("login_id", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("avatar_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Submissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canvas_id", models.CharField(max_length=255, unique=True)),
                ("submitted_at", models.DateTimeField()),
                ("score", models.FloatField()),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="pages.assignments",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="pages.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAssignments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField()),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="pages.assignments",
                    ),
                ),
                (
                    "custom_tasks",
                    models.ManyToManyField(
                        related_name="student_assignments", to="pages.customtasks"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="pages.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quizzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canvas_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_at", models.DateTimeField()),
                ("time_limit", models.IntegerField()),
                ("quiz_type", models.CharField(max_length=255)),
                ("allowed_attempts", models.IntegerField()),
                ("file_ids", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="pages.courses",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignments",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="pages.courses",
            ),
        ),
    ]
