# Generated by Django 4.2.9 on 2024-11-15 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_estimated_time", models.CharField(max_length=255)),
                ("work_distribution", models.TextField()),
                ("break_and_buffer", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_breakdown",
                        to="pages.assignments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentBreakdownTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_number", models.IntegerField()),
                ("description", models.TextField()),
                ("estimated_time", models.CharField(max_length=255)),
                ("due_date", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                ("tips", models.TextField(blank=True, null=True)),
                ("priority", models.CharField(max_length=50)),
                ("distraction_mitigation", models.TextField(blank=True, null=True)),
                ("focus_techniques", models.TextField(blank=True, null=True)),
                ("reward", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "breakdown",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="pages.assignmentbreakdown",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YouTubeResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_resources",
                        to="pages.assignmentbreakdowntask",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="studentassignments",
            name="custom_tasks",
        ),
        migrations.DeleteModel(
            name="CustomTasks",
        ),
        migrations.AddField(
            model_name="studentassignments",
            name="breakdown",
            field=models.ManyToManyField(
                related_name="student_assignments", to="pages.assignmentbreakdown"
            ),
        ),
    ]
