# Generated by Django 4.2.9 on 2024-11-15 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_assignmentbreakdown_assignmentbreakdowntask_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignmentbreakdown",
            old_name="break_and_buffer",
            new_name="breaks_and_buffer",
        ),
    ]
