# Generated by Django 4.2.9 on 2024-11-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_assignmentbreakdown_focus_impprovement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentbreakdown",
            name="focus_impprovement",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentbreakdown",
            name="key_requirements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentbreakdown",
            name="milestone_rewards",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentbreakdown",
            name="motivation_boosters",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentbreakdown",
            name="potential_challenges",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentbreakdown",
            name="time_management",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentbreakdowntask",
            name="focus_techniques",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentbreakdowntask",
            name="potential_distractions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
