# Generated by Django 4.2.9 on 2024-11-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_assignments_assignment_id_courses_course_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignments",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="pages.courses",
            ),
        ),
        migrations.AlterField(
            model_name="assignments",
            name="assignment_id",
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name="courses",
            name="course_id",
            field=models.CharField(default=1, max_length=255),
        ),
    ]
