# Generated by Django 4.2.9 on 2024-11-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_assignments_course_alter_assignments_assignment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignments",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignments",
            name="points_possible",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignments",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
