# Generated by Django 4.2.9 on 2024-11-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_assignmentfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentfile",
            name="file_category",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assignmentfile",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="assignment_thumbnails/"
            ),
        ),
    ]
