# Generated by Django 4.2.9 on 2024-11-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_assignmentfile_file_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentfile",
            name="claude_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
