# Generated by Django 4.2.9 on 2024-12-03 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_assignmentfile_chunk_embeddings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentfile",
            name="thumbnail",
        ),
        migrations.CreateModel(
            name="Modules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("position", models.IntegerField(default=0)),
                ("unlock_at", models.DateTimeField(blank=True, null=True)),
                ("require_sequential_progress", models.BooleanField(default=False)),
                ("publish_final_grade", models.BooleanField(default=False)),
                ("prerequisite_module_ids", models.JSONField(blank=True, default=list)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="pages.courses",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ModuleItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("position", models.IntegerField(default=0)),
                ("indent", models.IntegerField(default=0)),
                ("type", models.CharField(max_length=50)),
                ("content_id", models.CharField(blank=True, max_length=255, null=True)),
                ("html_url", models.URLField(blank=True, max_length=500)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("completion_requirement", models.JSONField(blank=True, default=dict)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pages.modules",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
