# Generated by Django 4.2.9 on 2024-12-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_alter_modules_options_modules_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moduleitems",
            options={
                "ordering": ["position"],
                "verbose_name": "Module Item",
                "verbose_name_plural": "Module Items",
            },
        ),
        migrations.AddField(
            model_name="moduleitems",
            name="content_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="moduleitems",
            name="external_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="moduleitems",
            name="new_tab",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="moduleitems",
            name="page_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="moduleitems",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
